site_name: CANOPIE-HPC
repo_name: supercontainers/canopie-hpc
repo_url: https://github.com/supercontainers/canopie-hpc 
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.sticky
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
extra:
  social:
    - icon: fontawesome/brands/slack
      link: http://bit.ly/hpccslack
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Call for Papers: cfp.md
  - Topics: topics.md
  - Organizers: organizers.md
  - Program: program.md
  - Previous Workshops:
    - SC21: prev/2021/index.md
    - SC20: prev/2020/index.md
    - SC19:
      - Home: prev/2019/index.md
      - Call for Papers: prev/2019/cfp.md
      - Organizers: prev/2019/org.md
      - Program: prev/2019/program.md
      - Topics: prev/2019/topic.md

